# https://doc.qt.io/qt-6/macos.html
c_stdlib_version:              # [osx and x86_64]
  - '11.0'                     # [osx and x86_64]
MACOSX_SDK_VERSION:            # [osx and x86_64]
  - '12.3'                     # [osx and x86_64]

qt_version:
  - none
  - 6          # [not ppc64le]

# Must use for Qt 6.9 https://bugreports.qt.io/browse/QTBUG-135452
# https://github.com/conda-forge/opencv-feedstock/pull/465#issuecomment-2854148414
c_compiler:    # [win]
- vs2022       # [win]
cxx_compiler:  # [win]
- vs2022       # [win]
