# eigen 3.4 is incompatible with vs2017
# therefore, we bump to 2019 before the conda-forge
# wide bump
# https://github.com/opencv/opencv/issues/21675
c_compiler:                    # [win]
  - vs2019                     # [win]
cxx_compiler:                  # [win]
  - vs2019                     # [win]
