# https://doc.qt.io/qt-6/macos.html
c_stdlib_version:              # [osx and qt_version == 6]
  - '11.0'                     # [osx and qt_version == 6]
MACOSX_SDK_VERSION:            # [osx and qt_version == 6]
  - '12.3'                     # [osx and qt_version == 6]

# As of 2024/03 -- OSX basically never had qt builds. If somebody asks, we can build them
# As of 2024/03 -- qt6 works better than qt5 on aarch64. So drop qt5.
# As of 2024/05 -- We had trouble gettin the aarch64 builds to work well with Qt6 and import cv2 on the CIs.
#                  We can re-consider adding Qt6 support for Aarch upon request.
# As of openCV 4.11 we dropped Qt5
qt_version:
  - none
  - 6          # [win or linux64]

# hmaarrfk - Jan 31, 2025
# Tensorflow is behind the protobuf migration
# tensorflow + opencv is a common combination
# Since we have tensorflow for linux64 and osx on conda-forge
# lets build out both of these versions for end users to alleviate
# accidentally downgrading their packages
# https://github.com/conda-forge/opencv-feedstock/issues/450
# Gotta keep libopenvino in sync too
# The first and last version to have 5.27.5 was libopenvino 2024.4.0
# https://github.com/conda-forge/openvino-feedstock/pull/107
# https://github.com/conda-forge/openvino-feedstock/pull/108
# Gotta also keep harbuzz in sync too
libprotobuf:          # [osx or linux64]
  - 5.27.5            # [osx or linux64]
  - 5.28.3            # [osx or linux64]
libopenvino_dev:      # [osx or linux64]
  - 2024.4.0          # [osx or linux64]
  - 2024.6.0          # [osx or linux64]
harfbuzz:             # [osx or linux64]
  - 9                 # [osx or linux64]
  - 10                # [osx or linux64]
zip_keys:             # [osx or linux64]
- - libprotobuf       # [osx or linux64]
  - libopenvino_dev   # [osx or linux64]
  - harfbuzz          # [osx or linux64]
