MACOSX_SDK_VERSION:            # [osx and x86_64]
  - "10.13"                    # [osx and x86_64]
MACOSX_DEPLOYMENT_TARGET:      # [osx and x86_64]
  - "10.13"                    # [osx and x86_64]

# Save the size of our build matrix.
# Build with older protobuf upon request
# https://github.com/conda-forge/libprotobuf-feedstock/issues/198
# hmaarrfk - 2023/10 - requested to have builds for linux64
# 4.23.4 is the latest protobuf migration
# 3.21 is the version that tensorflow 2.13 was last built with
libprotobuf:  # [linux64]
- '4.24.3'    # [linux64]
- '3.21'      # [linux64]

libgrpc:      # [linux64]
- '1.58'      # [linux64]
- '1.54'      # [linux64]

zip_keys:            # [linux64]
  -                  # [linux64]
    - libgrpc        # [linux64]
    - libprotobuf    # [linux64]
