MACOSX_SDK_VERSION:            # [osx and x86_64 and qt_version!=6]
  - "10.13"                    # [osx and x86_64 and qt_version!=6]
MACOSX_DEPLOYMENT_TARGET:      # [osx and x86_64 and qt_version!=6]
  - "10.13"                    # [osx and x86_64 and qt_version==none]
  - "10.13"                    # [osx and x86_64 and qt_version==5]

# https://doc.qt.io/qt-6/macos.html
MACOSX_DEPLOYMENT_TARGET:      # [osx and qt_version == 6]
  - '11.0'                     # [osx and qt_version == 6]
MACOSX_SDK_VERSION:            # [osx and qt_version == 6]
  - '12.3'                     # [osx and qt_version == 6]

qt_version:
  - none
  - 5          # [not ppc64le]
  - 6          # [not ppc64le]
