{% set version = "4.1.0" %}
{% set blas_variant = "openblas" %}

package:
  name: opencv
  version: {{ version }}

source:
  - url: https://github.com/opencv/opencv/archive/{{ version }}.tar.gz
    fn: opencv-{{ version }}.tar.gz
    sha256: 8f6e4ab393d81d72caae6e78bd0fd6956117ec9f006fba55fcdb88caf62989b7
  - url: https://github.com/opencv/opencv_contrib/archive/{{ version }}.tar.gz
    fn: opencv_contrib-{{ version }}.tar.gz
    sha256: e7d775cc0b87b04308823ca518b11b34cc12907a59af4ccdaf64419c1ba5e682
    folder: opencv_contrib

build:
  number: 2
  # Python2.7 support dropped: https://github.com/opencv/opencv/issues/8481
  skip: true  # [win and py27]

requirements:
  build:
    # Required to find ffpmeg
    - pkg-config                     # [not win]
    - m2-patch                       # [win]
    - cmake
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}        # [linux]
    - {{ cdt('libxdamage') }}        # [linux]
    - {{ cdt('libxfixes') }}         # [linux]
    - {{ cdt('libxxf86vm') }}        # [linux]
  host:
    - python
    - numpy
    - hdf5                           # [unix]
    - eigen 3.3.*
    - jasper                         # [unix]
    - zlib
    - jpeg
    - libtiff
    - libwebp
    - harfbuzz                       # [unix]
    - libpng
    - ffmpeg 4.1.*                   # [not win]
    - gstreamer                      # [linux]
    - gst-plugins-base               # [linux]
    - qt                             # [not osx]
    - liblapacke
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - hdf5                           # [unix]
    - jasper                         # [unix]
    - zlib
    - jpeg
    - libwebp
    - harfbuzz                       # [unix]
    - libtiff
    - libpng
    - ffmpeg 4.1.*                   # [not win]
    - qt                             # [not osx]

test:
    requires:
      - {{ compiler('c') }}
      - {{ compiler('cxx') }}
      - requests
      - certifi
      - pkg-config                 # [not win]
    imports:
      - cv2
      - cv2.xfeatures2d

    commands:
        # Verify dynamic libraries on all systems
        {% set win_ver_lib = version|replace(".", "") %}
        {% set opencv_libs = [
            "aruco",
            "bgsegm",
            "calib3d",
            "ccalib",
            "core",
            "datasets",
            "dnn",
            "dpm",
            "face",
            "features2d",
            "flann",
            "fuzzy",
            "highgui",
            "imgcodecs",
            "imgproc",
            "line_descriptor",
            "ml",
            "objdetect",
            "optflow",
            "phase_unwrapping",
            "photo",
            "plot",
            "reg",
            "rgbd",
            "saliency",
            "shape",
            "stereo",
            "stitching",
            "structured_light",
            "superres",
            "surface_matching",
            "text",
            "tracking",
            "video",
            "videoio",
            "videostab",
            "xfeatures2d",
            "ximgproc",
            "xobjdetect",
            "xphoto"
        ] %}
        - export MACOSX_DEPLOYMENT_TARGET={{ MACOSX_DEPLOYMENT_TARGET }}       # [osx]
        - export CONDA_BUILD_SYSROOT={{ CONDA_BUILD_SYSROOT }}                 # [osx]
        - OPENCV_FLAGS=`pkg-config --cflags opencv4`  # [unix]
        - $CXX -std=c++11 $RECIPE_DIR/test.cpp ${OPENCV_FLAGS} -o test   # [unix]
        - if [[ $(./test) != $PKG_VERSION ]]; then exit 1 ; fi                # [unix]
        - if [[ $($PYTHON -c 'import cv2; print(cv2.__version__)') != $PKG_VERSION ]]; then exit 1; fi  # [unix]
        {% for each_opencv_lib in opencv_libs %}
        - test -f $PREFIX/lib/libopencv_{{ each_opencv_lib }}${SHLIB_EXT}                  # [unix]
        - if not exist %PREFIX%\\Library\\bin\\opencv_{{ each_opencv_lib }}{{ win_ver_lib }}.dll exit 1  # [win]
        {% endfor %}
        - test -f $PREFIX/lib/libopencv_bioinspired${SHLIB_EXT}  # [unix]
        - test -f $PREFIX/lib/libopencv_hdf${SHLIB_EXT}          # [unix]
        - test -f $PREFIX/lib/libopencv_freetype${SHLIB_EXT}     # [unix]
        - test -f $PREFIX/lib/libopencv_videoio_gstreamer${SHLIB_EXT}  # [linux]
        - test -f $PREFIX/lib/libopencv_videoio_ffmpeg${SHLIB_EXT}     # [linux]

about:
  home: http://opencv.org/
  license: BSD 3-clause
  summary: Computer vision and machine learning software library.
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - patricksnape
    - zym1010
    - hajapy
    - ocefpaf
    - hmaarrfk
