{% set version = "2.4.13" %}
{% set filename = "opencv-%s.zip" % version %}

package:
  name: opencv
  version: {{ version }}

source:
  fn: {{ filename }}
  url: https://github.com/opencv/opencv/archive/{{ version }}.zip
  sha1: 0c6e4d890f6252ae8feae0c92f397f63aaa41a08

  patches:
    - osx_rpath.patch  # [osx]

build:
  number: 0
  skip: true  # [not py27]

requirements:
  build:
    - toolchain
    - cmake
    - python
    - numpy x.x
    - eigen 3.*
    - jasper   # [unix]
    - zlib 1.2*
    - jpeg 9*
    - libtiff 4.0.*
    - libpng 1.6*

  run:
    - python
    - numpy x.x
    - jasper   # [unix]
    - zlib 1.2*
    - jpeg 9*
    - libtiff 4.0.*
    - libpng 1.6*

test:
  imports:
    - cv2
    - cv2.cv
  commands:
    # Verify dynamic libraries.
    {% set opencv_libs = [
            "core",
            "flann",
            "imgproc",
            "highgui",
            "features2d",
            "calib3d",
            "ml",
            "video",
            "legacy",
            "objdetect",
            "photo",
            "gpu",
            "nonfree",
            "contrib",
            "stitching",
            "superres",
            "videostab"
    ] %}
    {% for each_opencv_lib in opencv_libs %}
    - test -f $PREFIX/lib/libopencv_{{ each_opencv_lib }}.dylib   # [osx]
    - test -f $PREFIX/lib/libopencv_{{ each_opencv_lib }}.so      # [linux]
    {% endfor %}

about:
  home: http://opencv.org/
  license: BSD 3-clause
  summary: Computer vision and machine learning software library.

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - patricksnape
