{% set version = "2.4.13.4" %}
{% set filename = "opencv2-%s.zip" % version %}
{% set blas_variant = "openblas" %}

package:
  name: opencv
  version: {{ version }}

source:
  fn: {{ filename }}
  url: https://github.com/Itseez/opencv/archive/{{ version }}.zip
  sha1: 34224584e570848b942685be7e5779f843f73a44

  patches:
    - osx_rpath.patch  # [osx]

build:
  number: 0
  skip: true  # [not py27]
  features:                    # [not win]
    - blas_{{ blas_variant }}  # [not win]

requirements:
  build:
    - toolchain
    - cmake
    - python
    - numpy 1.8.*
    - eigen 3.2.*
    - jasper                       # [unix]
    - zlib 1.2.11
    - jpeg 9*
    - libtiff >=4.0.3,<4.0.8
    - libpng >=1.6.22,<1.6.31
    - ffmpeg >=3.2.3,<3.2.6        # [not win]
    - openblas 0.2.20|0.2.20.*     # [not win]
    - blas 1.1 {{ blas_variant }}  # [not win]

  run:
    - python
    - numpy >=1.8
    - jasper                       # [unix]
    - zlib 1.2.11
    - jpeg 9*
    - libtiff >=4.0.3,<4.0.8
    - libpng >=1.6.22,<1.6.31
    - ffmpeg >=3.2.3,<3.2.6        # [not win]
    - openblas 0.2.20|0.2.20.*     # [not win]
    - blas 1.1 {{ blas_variant }}  # [not win]

test:
  requires:
    - requests
    - certifi
  imports:
    - cv2
    - cv2.cv
  commands:
    # Verify dynamic libraries.
    {% set opencv_libs = [
            "core",
            "flann",
            "imgproc",
            "highgui",
            "features2d",
            "calib3d",
            "ml",
            "video",
            "legacy",
            "objdetect",
            "photo",
            "gpu",
            "nonfree",
            "contrib",
            "stitching",
            "superres",
            "videostab"
    ] %}
    {% for each_opencv_lib in opencv_libs %}
    - test -f $PREFIX/lib/libopencv_{{ each_opencv_lib }}.dylib   # [osx]
    - test -f $PREFIX/lib/libopencv_{{ each_opencv_lib }}.so      # [linux]
    {% endfor %}

about:
  home: http://opencv.org/
  license: BSD 3-clause
  summary: Computer vision and machine learning software library.

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - patricksnape
    - zym1010
    - hajapy
    - ocefpaf
