{% set version = "4.1.1" %}

package:
  name: opencv_testing
  version: {{ version }}

source:
  - url: https://github.com/opencv/opencv/archive/{{ version }}.tar.gz
    fn: opencv-{{ version }}.tar.gz
    sha256: 5de5d96bdfb9dad6e6061d70f47a0a91cee96bb35afb9afb9ecb3d43e243d217
    patches:
        - 0001-cmake-download-tries-customizable-download-parameter.patch
        - 0001-Fix-for-building-with-old-V4L.patch
  - url: https://github.com/opencv/opencv_contrib/archive/{{ version }}.tar.gz
    fn: opencv_contrib-{{ version }}.tar.gz
    sha256: 9f85d380758498d800fec26307e389620cde8b1a2e86ab51cddc5200fbe37102
    folder: opencv_contrib

build:
  number: 0
  # Python2.7 support dropped: https://github.com/opencv/opencv/issues/8481
  skip: true  # [win and py27]
  script:
    - echo hi

requirements:
  host:
    - python
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
    requires:
      - opencv
      - freetype 2.9
    imports:
      - cv2

about:
  home: http://opencv.org/
  license: BSD 3-clause
  summary: Computer vision and machine learning software library.
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - patricksnape
    - zym1010
    - hajapy
    - ocefpaf
    - hmaarrfk
