{% set version = "2.4.12" %}
{% set filename = "opencv2-%s.zip" % version %}
{% set jpeg_version = os.environ.get('JPEG_VERSION', '9')|string %}
{% set libpng_version = os.environ.get('LIBPNG_VERSION', '>=1.6.21,<1.7')|string %}
{% set libpng_string = libpng_version.split(',')[0].split('=')[-1].replace('"', '') %}
{% set build_number = "3" %}

package:
  name: opencv
  version: {{ version }}

source:
  fn: {{ filename }}
  url: https://github.com/Itseez/opencv/archive/{{ version }}.zip
  sha1: 2225768a48dbf99426bf77451a433ed432f54d8e

  patches:
    - osx_rpath.patch  # [osx]

build:
  number: {{ build_number }}
  string: py{{ environ.get('CONDA_PY', '') }}_jpeg{{ jpeg_version }}_libpng{{ libpng_string }}_{{ build_number }}
  skip: true  # [not py27]

requirements:
  build:
    - cmake
    - python
    - numpy x.x
    - eigen 3.*
    - jasper   # [unix]
    - zlib 1.2*
    - libtiff 4.0.*
    - libpng {{ libpng_version }}
    - jpeg {{ jpeg_version }}*

  run:
    - python
    - numpy x.x
    - jasper   # [unix]
    - zlib 1.2*
    - libtiff 4.0.*
    - libpng {{ libpng_version }}
    - jpeg {{ jpeg_version }}*

test:
  imports:
    - cv2
    - cv2.cv
  commands:
    # Verify dynamic libraries.
    {% set opencv_libs = [
            "core",
            "flann",
            "imgproc",
            "highgui",
            "features2d",
            "calib3d",
            "ml",
            "video",
            "legacy",
            "objdetect",
            "photo",
            "gpu",
            "nonfree",
            "contrib",
            "stitching",
            "superres",
            "videostab"
    ] %}
    {% for each_opencv_lib in opencv_libs %}
    - test -f $PREFIX/lib/libopencv_{{ each_opencv_lib }}.dylib   # [osx]
    - test -f $PREFIX/lib/libopencv_{{ each_opencv_lib }}.so      # [linux]
    {% endfor %}

about:
  home: http://opencv.org/
  license: BSD 3-clause
  summary: Computer vision and machine learning software library.

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - patricksnape
    - 183amir
