{% set version = "3.4.2" %}
{% set blas_variant = "openblas" %}

package:
  name: opencv
  version: {{ version }}

source:
  - url: https://github.com/opencv/opencv/archive/{{ version }}.tar.gz
    fn: opencv-{{ version }}.tar.gz
    sha256: 81dbd5e7e9f8a4c936b94629bf4765745942a1d634ae38ec08bc57b73b28ffc5
  - url: https://github.com/opencv/opencv_contrib/archive/{{ version }}.tar.gz
    fn: opencv_contrib-{{ version }}.tar.gz
    sha256: 45a52764ebd2558fa0b7fd8dc47379b37dd0956d912abbf7c786228374fdf60d
    folder: opencv_contrib-{{ version }}

build:
  number: 200
  # Python2.7 support dropped: https://github.com/opencv/opencv/issues/8481
  skip: true  # [win and py27]
  features:                        # [not win]
    - blas_{{ blas_variant }}      # [not win]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pkgconfig                    # [unix]
    - numpy
    - hdf5                         # [unix]
    - eigen 3.2.*
    - jasper                       # [unix]
    - zlib
    - jpeg
    - libtiff
    - libwebp
    - harfbuzz                     # [unix]
    - libpng
    - openblas                     # [not win]
    - blas 1.1 {{ blas_variant }}  # [not win]
    - ffmpeg                       # [not win]
    - qt                           # [not osx]

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - hdf5                         # [unix]
    - jasper                       # [unix]
    - zlib
    - jpeg
    - libwebp
    - harfbuzz                     # [unix]
    - libtiff
    - libpng
    - openblas                     # [not win]
    - blas 1.1 {{ blas_variant }}  # [not win]
    - ffmpeg                       # [not win]
    - qt                           # [not osx]

test:
    requires:
      - requests
      - certifi
    imports:
      - cv2
      - cv2.xfeatures2d

    commands:
        # Verify dynamic libraries on all systems
        {% set win_ver_lib = version|replace(".", "") %}
        {% set opencv_libs = [
            "aruco",
            "bgsegm",
            "calib3d",
            "ccalib",
            "core",
            "datasets",
            "dnn",
            "dpm",
            "face",
            "features2d",
            "flann",
            "fuzzy",
            "highgui",
            "imgcodecs",
            "imgproc",
            "line_descriptor",
            "ml",
            "objdetect",
            "optflow",
            "phase_unwrapping",
            "photo",
            "plot",
            "reg",
            "rgbd",
            "saliency",
            "shape",
            "stereo",
            "stitching",
            "structured_light",
            "superres",
            "surface_matching",
            "text",
            "tracking",
            "video",
            "videoio",
            "videostab",
            "xfeatures2d",
            "ximgproc",
            "xobjdetect",
            "xphoto"
        ] %}
        {% for each_opencv_lib in opencv_libs %}
        - test -f $PREFIX/lib/libopencv_{{ each_opencv_lib }}${SHLIB_EXT}                  # [unix]
        - if not exist %PREFIX%\\Library\\bin\\opencv_{{ each_opencv_lib }}{{ win_ver_lib }}.dll exit 1  # [win]
        {% endfor %}
        - test -f $PREFIX/lib/libopencv_bioinspired${SHLIB_EXT}  # [unix]
        - test -f $PREFIX/lib/libopencv_hdf${SHLIB_EXT}          # [unix]
        - test -f $PREFIX/lib/libopencv_freetype${SHLIB_EXT}     # [unix]

about:
  home: http://opencv.org/
  license: BSD 3-clause
  summary: Computer vision and machine learning software library.

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - patricksnape
    - zym1010
    - hajapy
    - ocefpaf
