matrix:
  # default channel anaconda 4 requirements
  - [[JPEG_VERSION, 8], [LIBPNG_VERSION, '"1.6.17"']]
  # conda-forge channel requirements.
  - [[JPEG_VERSION, 9], [LIBPNG_VERSION, '">=1.6.21,<1.7"']]
travis:
  secure:
    BINSTAR_TOKEN: cCqLoE0MXFjPh08A3yFKEWeA7/aRpHUeTxgfJPv9/5MqIzXHjChT7/FZ9kBvxoB2alWQ3DefqLaBX5YoAoDIWUZ2xCxLyJ1vqVicoqh+TmievNkzpu65EMtBBWoFZhSyJXqZ4NhHm4W+WxwrlBEboYTxLsEh41AVoEJg/XIC5ON53NHGxFHuMxtnNyWFIMXj/cJAC+KVhCVysGJ8mLJJdmBvIjOXtfz2Y7k9lXPdMV7taqoxdC02ZDaoAt7sfvARAjsQQZh852RBMB4/qkRMGoywOJUXj+BQx2TCYgAKrYz9WzaST0NzYXQIkrtlbFD045vBvOWUZ+F1L91V1SuCQ5iWjkpdMyEH1gh+E4pSPM9hjP/L5KWrs1AX9vybt7OTBMKo/VI+er1kb0vOZMHyXY6FYG4QDJlfDrcY12vJzEM7WpFldbL3Jq2WRWJzl8ToYBwXmFNl9x+466bxKMhnYUAkx5uhEcZQRhLG2V6LWQr6rgdkAOM7kzDO8NjewX00W1K3HukmjFvCAFuZOAdpLb2lgerb0e69GzBiSqEdhByyerXht4q19xtCmJZBjy54SdyktiyGm+mvnGDo/6/ThRjCOzwIuLqxlK8WpWNXBAmgfY5dqwEMhACs1AP4uxVk4X4sVsHk86qMVEY9S3ZB/E2LMeMZBn0E9B1tu5q/Au0=
appveyor:
  secure:
    BINSTAR_TOKEN: /XxwAsgp0EItmAhoPSov/h0BtAFNj2BuuEqnhgaP9l7Rw2yLBM1lD+3q4LvpVm3B
