appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
  image: Visual Studio 2017
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: gjxs9T6fBaQ9aZVBgJbHlOHH2nIke+diMvfkFMXDIyJq0O9vcA3hrv7TQ79OI3ny7TrQA9ZzZFWyUdjf9TXVDHDfaePqCYpfiuZhzNQ+0ZPEdOvcDo66BWa1jB7v1Qg9VSOvYZZ2j5TyrCFO5WXg3UQKXvuU4V9rDwuO/JgNO/5mF7SOERJQn1Bgu9Ho2DLSUnHW6m23QmfongY/eioM557jK8pnlG8qH7RavArRlHv2MUYhBJNgNBt1RIq1LCTtEefUYePvte7YzVI74H1cVFYwVPb/2+glNVUxexvVB582KtnDvDhaEkkkRmUYeMzAFL30SVRT9YLt5QjwVtYP9RAoeWZ38SSpKM1UBuKLZ8El19cDhNoCR3Q0lo4EhUk4dmBtq1EyZiYGIhmk10yKDe+6dEEoV9kVA7vEXtHgaSh/gISPOt74YKeWgLqe+JexHfQf9j8xkhtVKQ30iYNqt1pEBe2ydST2EKzTSiPN95TR6b7+QVEIRhO1tWe27Yjh/slNkvydoUm2wqjAoTxQMjFA1Vkt5dJfzjQ1TdiUEzegktKu3C81jLr9Mc0UtvGdMiDBixaL0ZFSzLgdIHL0tY3s//psjf4d6JS8FhXASQOjoqwLNDc4qgJkqvwN1UgYe36VzotNmcihI0TMMfHHZGCxAivr3hOQQ1lVk1OhUCM=}
