# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: win
  pool:
    vmImage: windows-2022
  strategy:
    matrix:
      win_64_hdf51.14.6python3.10.____cpythonqt_version6:
        CONFIG: win_64_hdf51.14.6python3.10.____cpythonqt_version6
        UPLOAD_PACKAGES: 'True'
        build_workspace_dir: D:\\bld\\
        free_disk_space: skip
        pagefile_size: 0
        resize_partitions: false
        store_build_artifacts: false
        tools_install_dir: D:\Miniforge
      win_64_hdf51.14.6python3.10.____cpythonqt_versionnone:
        CONFIG: win_64_hdf51.14.6python3.10.____cpythonqt_versionnone
        UPLOAD_PACKAGES: 'True'
        build_workspace_dir: D:\\bld\\
        free_disk_space: skip
        pagefile_size: 0
        resize_partitions: false
        store_build_artifacts: false
        tools_install_dir: D:\Miniforge
      win_64_hdf51.14.6python3.11.____cpythonqt_version6:
        CONFIG: win_64_hdf51.14.6python3.11.____cpythonqt_version6
        UPLOAD_PACKAGES: 'True'
        build_workspace_dir: D:\\bld\\
        free_disk_space: skip
        pagefile_size: 0
        resize_partitions: false
        store_build_artifacts: false
        tools_install_dir: D:\Miniforge
      win_64_hdf51.14.6python3.11.____cpythonqt_versionnone:
        CONFIG: win_64_hdf51.14.6python3.11.____cpythonqt_versionnone
        UPLOAD_PACKAGES: 'True'
        build_workspace_dir: D:\\bld\\
        free_disk_space: skip
        pagefile_size: 0
        resize_partitions: false
        store_build_artifacts: false
        tools_install_dir: D:\Miniforge
      win_64_hdf51.14.6python3.12.____cpythonqt_version6:
        CONFIG: win_64_hdf51.14.6python3.12.____cpythonqt_version6
        UPLOAD_PACKAGES: 'True'
        build_workspace_dir: D:\\bld\\
        free_disk_space: skip
        pagefile_size: 0
        resize_partitions: false
        store_build_artifacts: false
        tools_install_dir: D:\Miniforge
      win_64_hdf51.14.6python3.12.____cpythonqt_versionnone:
        CONFIG: win_64_hdf51.14.6python3.12.____cpythonqt_versionnone
        UPLOAD_PACKAGES: 'True'
        build_workspace_dir: D:\\bld\\
        free_disk_space: skip
        pagefile_size: 0
        resize_partitions: false
        store_build_artifacts: false
        tools_install_dir: D:\Miniforge
      win_64_hdf51.14.6python3.13.____cp313qt_version6:
        CONFIG: win_64_hdf51.14.6python3.13.____cp313qt_version6
        UPLOAD_PACKAGES: 'True'
        build_workspace_dir: D:\\bld\\
        free_disk_space: skip
        pagefile_size: 0
        resize_partitions: false
        store_build_artifacts: false
        tools_install_dir: D:\Miniforge
      win_64_hdf51.14.6python3.13.____cp313qt_versionnone:
        CONFIG: win_64_hdf51.14.6python3.13.____cp313qt_versionnone
        UPLOAD_PACKAGES: 'True'
        build_workspace_dir: D:\\bld\\
        free_disk_space: skip
        pagefile_size: 0
        resize_partitions: false
        store_build_artifacts: false
        tools_install_dir: D:\Miniforge
      win_64_hdf51.14.6python3.14.____cp314qt_version6:
        CONFIG: win_64_hdf51.14.6python3.14.____cp314qt_version6
        UPLOAD_PACKAGES: 'True'
        build_workspace_dir: D:\\bld\\
        free_disk_space: skip
        pagefile_size: 0
        resize_partitions: false
        store_build_artifacts: false
        tools_install_dir: D:\Miniforge
      win_64_hdf51.14.6python3.14.____cp314qt_versionnone:
        CONFIG: win_64_hdf51.14.6python3.14.____cp314qt_versionnone
        UPLOAD_PACKAGES: 'True'
        build_workspace_dir: D:\\bld\\
        free_disk_space: skip
        pagefile_size: 0
        resize_partitions: false
        store_build_artifacts: false
        tools_install_dir: D:\Miniforge
      win_64_hdf52python3.10.____cpythonqt_version6:
        CONFIG: win_64_hdf52python3.10.____cpythonqt_version6
        UPLOAD_PACKAGES: 'True'
        build_workspace_dir: D:\\bld\\
        free_disk_space: skip
        pagefile_size: 0
        resize_partitions: false
        store_build_artifacts: false
        tools_install_dir: D:\Miniforge
      win_64_hdf52python3.10.____cpythonqt_versionnone:
        CONFIG: win_64_hdf52python3.10.____cpythonqt_versionnone
        UPLOAD_PACKAGES: 'True'
        build_workspace_dir: D:\\bld\\
        free_disk_space: skip
        pagefile_size: 0
        resize_partitions: false
        store_build_artifacts: false
        tools_install_dir: D:\Miniforge
      win_64_hdf52python3.11.____cpythonqt_version6:
        CONFIG: win_64_hdf52python3.11.____cpythonqt_version6
        UPLOAD_PACKAGES: 'True'
        build_workspace_dir: D:\\bld\\
        free_disk_space: skip
        pagefile_size: 0
        resize_partitions: false
        store_build_artifacts: false
        tools_install_dir: D:\Miniforge
      win_64_hdf52python3.11.____cpythonqt_versionnone:
        CONFIG: win_64_hdf52python3.11.____cpythonqt_versionnone
        UPLOAD_PACKAGES: 'True'
        build_workspace_dir: D:\\bld\\
        free_disk_space: skip
        pagefile_size: 0
        resize_partitions: false
        store_build_artifacts: false
        tools_install_dir: D:\Miniforge
      win_64_hdf52python3.12.____cpythonqt_version6:
        CONFIG: win_64_hdf52python3.12.____cpythonqt_version6
        UPLOAD_PACKAGES: 'True'
        build_workspace_dir: D:\\bld\\
        free_disk_space: skip
        pagefile_size: 0
        resize_partitions: false
        store_build_artifacts: false
        tools_install_dir: D:\Miniforge
      win_64_hdf52python3.12.____cpythonqt_versionnone:
        CONFIG: win_64_hdf52python3.12.____cpythonqt_versionnone
        UPLOAD_PACKAGES: 'True'
        build_workspace_dir: D:\\bld\\
        free_disk_space: skip
        pagefile_size: 0
        resize_partitions: false
        store_build_artifacts: false
        tools_install_dir: D:\Miniforge
      win_64_hdf52python3.13.____cp313qt_version6:
        CONFIG: win_64_hdf52python3.13.____cp313qt_version6
        UPLOAD_PACKAGES: 'True'
        build_workspace_dir: D:\\bld\\
        free_disk_space: skip
        pagefile_size: 0
        resize_partitions: false
        store_build_artifacts: false
        tools_install_dir: D:\Miniforge
      win_64_hdf52python3.13.____cp313qt_versionnone:
        CONFIG: win_64_hdf52python3.13.____cp313qt_versionnone
        UPLOAD_PACKAGES: 'True'
        build_workspace_dir: D:\\bld\\
        free_disk_space: skip
        pagefile_size: 0
        resize_partitions: false
        store_build_artifacts: false
        tools_install_dir: D:\Miniforge
      win_64_hdf52python3.14.____cp314qt_version6:
        CONFIG: win_64_hdf52python3.14.____cp314qt_version6
        UPLOAD_PACKAGES: 'True'
        build_workspace_dir: D:\\bld\\
        free_disk_space: skip
        pagefile_size: 0
        resize_partitions: false
        store_build_artifacts: false
        tools_install_dir: D:\Miniforge
      win_64_hdf52python3.14.____cp314qt_versionnone:
        CONFIG: win_64_hdf52python3.14.____cp314qt_versionnone
        UPLOAD_PACKAGES: 'True'
        build_workspace_dir: D:\\bld\\
        free_disk_space: skip
        pagefile_size: 0
        resize_partitions: false
        store_build_artifacts: false
        tools_install_dir: D:\Miniforge
    maxParallel: 17
  timeoutInMinutes: 360
  variables:
    UPLOAD_TEMP: D:\\tmp

  steps:
    - script: |
        call ".scripts\run_win_build.bat"
      displayName: Run Windows build
      env:
        CI: azure
        CONFIG: $(CONFIG)
        CONDA_BLD_PATH: $(build_workspace_dir)
        MINIFORGE_HOME: $(tools_install_dir)
        PYTHONUNBUFFERED: 1
        UPLOAD_PACKAGES: $(UPLOAD_PACKAGES)
        UPLOAD_TEMP: $(UPLOAD_TEMP)
        flow_run_id: azure_$(Build.BuildNumber).$(System.JobAttempt)
        remote_url: $(Build.Repository.Uri)
        sha: $(Build.SourceVersion)
        BINSTAR_TOKEN: $(BINSTAR_TOKEN)
        FEEDSTOCK_TOKEN: $(FEEDSTOCK_TOKEN)
        STAGING_BINSTAR_TOKEN: $(STAGING_BINSTAR_TOKEN)
