# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

name: Build conda package
on:
  push:

  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    name: ${{ matrix.CONFIG }}
    runs-on: ${{ matrix.runs_on }}
    timeout-minutes: 360
    strategy:
      fail-fast: false
      max-parallel: 50
      matrix:
        include:
          - CONFIG: linux_64_hdf51.14.6is_abi3falseis_python_minfalsepython3.14.____cp314tqt_version6
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma10
            STORE_BUILD_ARTIFACTS: False
            UPLOAD_PACKAGES: True
            build_workspace_dir: build_artifacts
            docker_run_args: 
            free_disk_space: skip
            os: ubuntu
            pagefile_size: 0
            resize_partitions: False
            runs_on: ['ubuntu-latest']
            tools_install_dir: ~/miniforge3
          - CONFIG: linux_64_hdf51.14.6is_abi3falseis_python_minfalsepython3.14.____cp314tqt_versionnone
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma10
            STORE_BUILD_ARTIFACTS: False
            UPLOAD_PACKAGES: True
            build_workspace_dir: build_artifacts
            docker_run_args: 
            free_disk_space: skip
            os: ubuntu
            pagefile_size: 0
            resize_partitions: False
            runs_on: ['ubuntu-latest']
            tools_install_dir: ~/miniforge3
          - CONFIG: linux_64_hdf51.14.6is_abi3trueis_python_mintruepython3.10.____cpythonqt_version6
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma10
            STORE_BUILD_ARTIFACTS: False
            UPLOAD_PACKAGES: True
            build_workspace_dir: build_artifacts
            docker_run_args: 
            free_disk_space: skip
            os: ubuntu
            pagefile_size: 0
            resize_partitions: False
            runs_on: ['ubuntu-latest']
            tools_install_dir: ~/miniforge3
          - CONFIG: linux_64_hdf51.14.6is_abi3trueis_python_mintruepython3.10.____cpythonqt_versionnone
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma10
            STORE_BUILD_ARTIFACTS: False
            UPLOAD_PACKAGES: True
            build_workspace_dir: build_artifacts
            docker_run_args: 
            free_disk_space: skip
            os: ubuntu
            pagefile_size: 0
            resize_partitions: False
            runs_on: ['ubuntu-latest']
            tools_install_dir: ~/miniforge3
          - CONFIG: linux_64_hdf52is_abi3falseis_python_minfalsepython3.14.____cp314tqt_version6
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma10
            STORE_BUILD_ARTIFACTS: False
            UPLOAD_PACKAGES: True
            build_workspace_dir: build_artifacts
            docker_run_args: 
            free_disk_space: skip
            os: ubuntu
            pagefile_size: 0
            resize_partitions: False
            runs_on: ['ubuntu-latest']
            tools_install_dir: ~/miniforge3
          - CONFIG: linux_64_hdf52is_abi3falseis_python_minfalsepython3.14.____cp314tqt_versionnone
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma10
            STORE_BUILD_ARTIFACTS: False
            UPLOAD_PACKAGES: True
            build_workspace_dir: build_artifacts
            docker_run_args: 
            free_disk_space: skip
            os: ubuntu
            pagefile_size: 0
            resize_partitions: False
            runs_on: ['ubuntu-latest']
            tools_install_dir: ~/miniforge3
          - CONFIG: linux_64_hdf52is_abi3trueis_python_mintruepython3.10.____cpythonqt_version6
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma10
            STORE_BUILD_ARTIFACTS: False
            UPLOAD_PACKAGES: True
            build_workspace_dir: build_artifacts
            docker_run_args: 
            free_disk_space: skip
            os: ubuntu
            pagefile_size: 0
            resize_partitions: False
            runs_on: ['ubuntu-latest']
            tools_install_dir: ~/miniforge3
          - CONFIG: linux_64_hdf52is_abi3trueis_python_mintruepython3.10.____cpythonqt_versionnone
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma10
            STORE_BUILD_ARTIFACTS: False
            UPLOAD_PACKAGES: True
            build_workspace_dir: build_artifacts
            docker_run_args: 
            free_disk_space: skip
            os: ubuntu
            pagefile_size: 0
            resize_partitions: False
            runs_on: ['ubuntu-latest']
            tools_install_dir: ~/miniforge3
          - CONFIG: linux_aarch64_hdf51.14.6is_abi3falseis_python_minfalsepython3.14.____cp314tqt_version6
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma10
            STORE_BUILD_ARTIFACTS: False
            UPLOAD_PACKAGES: True
            build_workspace_dir: build_artifacts
            docker_run_args: 
            free_disk_space: skip
            os: ubuntu
            pagefile_size: 0
            resize_partitions: False
            runs_on: ['ubuntu-latest']
            tools_install_dir: ~/miniforge3
          - CONFIG: linux_aarch64_hdf51.14.6is_abi3falseis_python_minfalsepython3.14.____cp314tqt_versionnone
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma10
            STORE_BUILD_ARTIFACTS: False
            UPLOAD_PACKAGES: True
            build_workspace_dir: build_artifacts
            docker_run_args: 
            free_disk_space: skip
            os: ubuntu
            pagefile_size: 0
            resize_partitions: False
            runs_on: ['ubuntu-latest']
            tools_install_dir: ~/miniforge3
          - CONFIG: linux_aarch64_hdf51.14.6is_abi3trueis_python_mintruepython3.10.____cpythonqt_version6
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma10
            STORE_BUILD_ARTIFACTS: False
            UPLOAD_PACKAGES: True
            build_workspace_dir: build_artifacts
            docker_run_args: 
            free_disk_space: skip
            os: ubuntu
            pagefile_size: 0
            resize_partitions: False
            runs_on: ['ubuntu-latest']
            tools_install_dir: ~/miniforge3
          - CONFIG: linux_aarch64_hdf51.14.6is_abi3trueis_python_mintruepython3.10.____cpythonqt_versionnone
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma10
            STORE_BUILD_ARTIFACTS: False
            UPLOAD_PACKAGES: True
            build_workspace_dir: build_artifacts
            docker_run_args: 
            free_disk_space: skip
            os: ubuntu
            pagefile_size: 0
            resize_partitions: False
            runs_on: ['ubuntu-latest']
            tools_install_dir: ~/miniforge3
          - CONFIG: linux_aarch64_hdf52is_abi3falseis_python_minfalsepython3.14.____cp314tqt_version6
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma10
            STORE_BUILD_ARTIFACTS: False
            UPLOAD_PACKAGES: True
            build_workspace_dir: build_artifacts
            docker_run_args: 
            free_disk_space: skip
            os: ubuntu
            pagefile_size: 0
            resize_partitions: False
            runs_on: ['ubuntu-latest']
            tools_install_dir: ~/miniforge3
          - CONFIG: linux_aarch64_hdf52is_abi3falseis_python_minfalsepython3.14.____cp314tqt_versionnone
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma10
            STORE_BUILD_ARTIFACTS: False
            UPLOAD_PACKAGES: True
            build_workspace_dir: build_artifacts
            docker_run_args: 
            free_disk_space: skip
            os: ubuntu
            pagefile_size: 0
            resize_partitions: False
            runs_on: ['ubuntu-latest']
            tools_install_dir: ~/miniforge3
          - CONFIG: linux_aarch64_hdf52is_abi3trueis_python_mintruepython3.10.____cpythonqt_version6
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma10
            STORE_BUILD_ARTIFACTS: False
            UPLOAD_PACKAGES: True
            build_workspace_dir: build_artifacts
            docker_run_args: 
            free_disk_space: skip
            os: ubuntu
            pagefile_size: 0
            resize_partitions: False
            runs_on: ['ubuntu-latest']
            tools_install_dir: ~/miniforge3
          - CONFIG: linux_aarch64_hdf52is_abi3trueis_python_mintruepython3.10.____cpythonqt_versionnone
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma10
            STORE_BUILD_ARTIFACTS: False
            UPLOAD_PACKAGES: True
            build_workspace_dir: build_artifacts
            docker_run_args: 
            free_disk_space: skip
            os: ubuntu
            pagefile_size: 0
            resize_partitions: False
            runs_on: ['ubuntu-latest']
            tools_install_dir: ~/miniforge3
          - CONFIG: linux_ppc64le_hdf51.14.6is_abi3falseis_python_minfalsepython3.14.____cp314t
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma10
            STORE_BUILD_ARTIFACTS: False
            UPLOAD_PACKAGES: True
            build_workspace_dir: build_artifacts
            docker_run_args: 
            free_disk_space: skip
            os: ubuntu
            pagefile_size: 0
            resize_partitions: False
            runs_on: ['ubuntu-latest']
            tools_install_dir: ~/miniforge3
          - CONFIG: linux_ppc64le_hdf51.14.6is_abi3trueis_python_mintruepython3.10.____cpython
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma10
            STORE_BUILD_ARTIFACTS: False
            UPLOAD_PACKAGES: True
            build_workspace_dir: build_artifacts
            docker_run_args: 
            free_disk_space: skip
            os: ubuntu
            pagefile_size: 0
            resize_partitions: False
            runs_on: ['ubuntu-latest']
            tools_install_dir: ~/miniforge3
          - CONFIG: linux_ppc64le_hdf52is_abi3falseis_python_minfalsepython3.14.____cp314t
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma10
            STORE_BUILD_ARTIFACTS: False
            UPLOAD_PACKAGES: True
            build_workspace_dir: build_artifacts
            docker_run_args: 
            free_disk_space: skip
            os: ubuntu
            pagefile_size: 0
            resize_partitions: False
            runs_on: ['ubuntu-latest']
            tools_install_dir: ~/miniforge3
          - CONFIG: linux_ppc64le_hdf52is_abi3trueis_python_mintruepython3.10.____cpython
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma10
            STORE_BUILD_ARTIFACTS: False
            UPLOAD_PACKAGES: True
            build_workspace_dir: build_artifacts
            docker_run_args: 
            free_disk_space: skip
            os: ubuntu
            pagefile_size: 0
            resize_partitions: False
            runs_on: ['ubuntu-latest']
            tools_install_dir: ~/miniforge3
          - CONFIG: win_64_hdf51.14.6is_abi3falseis_python_minfalsepython3.14.____cp314tqt_version6
            STORE_BUILD_ARTIFACTS: False
            UPLOAD_PACKAGES: True
            build_platform: win-64
            build_workspace_dir: D:\\bld\\
            docker_run_args: 
            free_disk_space: skip
            os: windows
            pagefile_size: 0
            resize_partitions: False
            runs_on: ['windows-2022']
            tools_install_dir: D:\Miniforge
          - CONFIG: win_64_hdf51.14.6is_abi3falseis_python_minfalsepython3.14.____cp314tqt_versionnone
            STORE_BUILD_ARTIFACTS: False
            UPLOAD_PACKAGES: True
            build_platform: win-64
            build_workspace_dir: D:\\bld\\
            docker_run_args: 
            free_disk_space: skip
            os: windows
            pagefile_size: 0
            resize_partitions: False
            runs_on: ['windows-2022']
            tools_install_dir: D:\Miniforge
          - CONFIG: win_64_hdf51.14.6is_abi3trueis_python_mintruepython3.10.____cpythonqt_version6
            STORE_BUILD_ARTIFACTS: False
            UPLOAD_PACKAGES: True
            build_platform: win-64
            build_workspace_dir: D:\\bld\\
            docker_run_args: 
            free_disk_space: skip
            os: windows
            pagefile_size: 0
            resize_partitions: False
            runs_on: ['windows-2022']
            tools_install_dir: D:\Miniforge
          - CONFIG: win_64_hdf51.14.6is_abi3trueis_python_mintruepython3.10.____cpythonqt_versionnone
            STORE_BUILD_ARTIFACTS: False
            UPLOAD_PACKAGES: True
            build_platform: win-64
            build_workspace_dir: D:\\bld\\
            docker_run_args: 
            free_disk_space: skip
            os: windows
            pagefile_size: 0
            resize_partitions: False
            runs_on: ['windows-2022']
            tools_install_dir: D:\Miniforge
          - CONFIG: win_64_hdf52is_abi3falseis_python_minfalsepython3.14.____cp314tqt_version6
            STORE_BUILD_ARTIFACTS: False
            UPLOAD_PACKAGES: True
            build_platform: win-64
            build_workspace_dir: D:\\bld\\
            docker_run_args: 
            free_disk_space: skip
            os: windows
            pagefile_size: 0
            resize_partitions: False
            runs_on: ['windows-2022']
            tools_install_dir: D:\Miniforge
          - CONFIG: win_64_hdf52is_abi3falseis_python_minfalsepython3.14.____cp314tqt_versionnone
            STORE_BUILD_ARTIFACTS: False
            UPLOAD_PACKAGES: True
            build_platform: win-64
            build_workspace_dir: D:\\bld\\
            docker_run_args: 
            free_disk_space: skip
            os: windows
            pagefile_size: 0
            resize_partitions: False
            runs_on: ['windows-2022']
            tools_install_dir: D:\Miniforge
          - CONFIG: win_64_hdf52is_abi3trueis_python_mintruepython3.10.____cpythonqt_version6
            STORE_BUILD_ARTIFACTS: False
            UPLOAD_PACKAGES: True
            build_platform: win-64
            build_workspace_dir: D:\\bld\\
            docker_run_args: 
            free_disk_space: skip
            os: windows
            pagefile_size: 0
            resize_partitions: False
            runs_on: ['windows-2022']
            tools_install_dir: D:\Miniforge
          - CONFIG: win_64_hdf52is_abi3trueis_python_mintruepython3.10.____cpythonqt_versionnone
            STORE_BUILD_ARTIFACTS: False
            UPLOAD_PACKAGES: True
            build_platform: win-64
            build_workspace_dir: D:\\bld\\
            docker_run_args: 
            free_disk_space: skip
            os: windows
            pagefile_size: 0
            resize_partitions: False
            runs_on: ['windows-2022']
            tools_install_dir: D:\Miniforge
    steps:

    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Configure binfmt_misc
      if: matrix.os == 'ubuntu'
      shell: bash
      run: |
        if [[ "$(uname -m)" == "x86_64" ]]; then
          docker run --rm --privileged multiarch/qemu-user-static:register --reset --credential yes
        fi

    - name: Build on Linux
      id: build-linux
      if: matrix.os == 'ubuntu'
      env:
        CI: github_actions
        CONDA_BLD_PATH: ${{ matrix.build_workspace_dir }}
        CONDA_FORGE_DOCKER_RUN_ARGS: ${{ matrix.docker_run_args }}
        CONFIG: ${{ matrix.CONFIG }}
        MINIFORGE_HOME: ${{ matrix.tools_install_dir }}
        DOCKER_IMAGE: ${{ matrix.DOCKER_IMAGE }}
        UPLOAD_PACKAGES: ${{ matrix.UPLOAD_PACKAGES }}
        RATTLER_BUILD_COLOR: always
        RATTLER_BUILD_ENABLE_GITHUB_INTEGRATION: 'true'
        BINSTAR_TOKEN: ${{ secrets.BINSTAR_TOKEN }}
        FEEDSTOCK_TOKEN: ${{ secrets.FEEDSTOCK_TOKEN }}
        STAGING_BINSTAR_TOKEN: ${{ secrets.STAGING_BINSTAR_TOKEN }}
      shell: bash
      run: |
        export CONDA_BLD_PATH="${CONDA_BLD_PATH/#~/${HOME}}"
        export FEEDSTOCK_NAME="$(basename $GITHUB_REPOSITORY)"
        export GIT_BRANCH="${GITHUB_REF_NAME}"
        export MINIFORGE_HOME="${MINIFORGE_HOME/#~/${HOME}}"
        export flow_run_id="github_$GITHUB_RUN_ID"
        export remote_url="https://github.com/$GITHUB_REPOSITORY"
        export sha="$GITHUB_SHA"
        if [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
          export IS_PR_BUILD="True"
        else
          export IS_PR_BUILD="False"
        fi
        ./.scripts/run_docker_build.sh

    - name: Build on macOS
      id: build-macos
      if: matrix.os == 'macos'
      env:
        CI: github_actions
        CONDA_BLD_PATH: ${{ matrix.build_workspace_dir }}
        CONFIG: ${{ matrix.CONFIG }}
        MINIFORGE_HOME: ${{ matrix.tools_install_dir }}
        UPLOAD_PACKAGES: ${{ matrix.UPLOAD_PACKAGES }}
        RATTLER_BUILD_COLOR: always
        RATTLER_BUILD_ENABLE_GITHUB_INTEGRATION: 'true'
        BINSTAR_TOKEN: ${{ secrets.BINSTAR_TOKEN }}
        FEEDSTOCK_TOKEN: ${{ secrets.FEEDSTOCK_TOKEN }}
        STAGING_BINSTAR_TOKEN: ${{ secrets.STAGING_BINSTAR_TOKEN }}
      shell: bash
      run: |
        export CONDA_BLD_PATH="${CONDA_BLD_PATH/#~/${HOME}}"
        export FEEDSTOCK_NAME="$(basename $GITHUB_REPOSITORY)"
        export GIT_BRANCH="${GITHUB_REF_NAME}"
        export MINIFORGE_HOME="${MINIFORGE_HOME/#~/${HOME}}"
        export flow_run_id="github_$GITHUB_RUN_ID"
        export remote_url="https://github.com/$GITHUB_REPOSITORY"
        export sha="$GITHUB_SHA"
        if [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
          export IS_PR_BUILD="True"
        else
          export IS_PR_BUILD="False"
        fi
        ./.scripts/run_osx_build.sh

    - name: Build on windows
      id: build-windows
      if: matrix.os == 'windows'
      shell: cmd
      run: |
        set "flow_run_id=github_%GITHUB_RUN_ID%"
        set "remote_url=https://github.com/%GITHUB_REPOSITORY%"
        set "sha=%GITHUB_SHA%"
        call ".scripts\run_win_build.bat"
      env:
        BUILD_PLATFORM: ${{ matrix.build_platform }}
        CI: github_actions
        CONDA_BLD_PATH: ${{ matrix.build_workspace_dir }}
        CONFIG: ${{ matrix.CONFIG }}
        MINIFORGE_HOME: ${{ matrix.tools_install_dir }}
        PYTHONUNBUFFERED: 1
        UPLOAD_PACKAGES: ${{ matrix.UPLOAD_PACKAGES }}
        RATTLER_BUILD_COLOR: always
        RATTLER_BUILD_ENABLE_GITHUB_INTEGRATION: 'true'
        BINSTAR_TOKEN: ${{ secrets.BINSTAR_TOKEN }}
        FEEDSTOCK_TOKEN: ${{ secrets.FEEDSTOCK_TOKEN }}
        STAGING_BINSTAR_TOKEN: ${{ secrets.STAGING_BINSTAR_TOKEN }}